# Form implementation generated from reading ui file 'todolist.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(773, 501)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(80, 50, 561, 341))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Lucida Fax")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.add_task_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.add_task_btn.setObjectName("add_task_btn")
        self.verticalLayout.addWidget(self.add_task_btn)
        self.Table = QtWidgets.QTableView(parent=self.verticalLayoutWidget_2)
        self.Table.setObjectName("Table")
        self.verticalLayout.addWidget(self.Table)
        self.finish_task = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.finish_task.setObjectName("finish_task")
        self.verticalLayout.addWidget(self.finish_task)
        self.unfinish_task = QtWidgets.QLabel(parent=self.verticalLayoutWidget_2)
        self.unfinish_task.setObjectName("unfinish_task")
        self.verticalLayout.addWidget(self.unfinish_task)
        self.remove_all_btn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget_2)
        self.remove_all_btn.setObjectName("remove_all_btn")
        self.verticalLayout.addWidget(self.remove_all_btn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Danh sách việc cần làm"))
        self.add_task_btn.setText(_translate("MainWindow", "Thêm nhiệm vụ"))
        self.finish_task.setText(_translate("MainWindow", "Đã hoàn thành: "))
        self.unfinish_task.setText(_translate("MainWindow", "Chưa hoàn thành:"))
        self.remove_all_btn.setText(_translate("MainWindow", "Xóa tất cả"))

        self.add_task_btn.clicked.connect(self.add_task)

    def add_task(self):
        self.title.setText("Hehe")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
